/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa_principal;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PantallaP extends javax.swing.JFrame {
    private int pin;
    private String nombreCompleto;
    private String numeroTelefonico;
    private double saldoInicial;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaP.class.getName());

    public PantallaP(String nombreUsuario, String nombreCompleto, String numeroTelefonico) throws IOException {
    initComponents();
    
    this.nombreCompleto = nombreCompleto;
    this.numeroTelefonico = numeroTelefonico;
    
    this.setLocationRelativeTo(null);
    lblBienvenida.setText("Bienvenido, " + nombreUsuario + " 👋");

    LocalDateTime ahora = LocalDateTime.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
    lblFechaHora.setText("Fecha y hora actual: " + ahora.format(formato));

    saldoInicial = 1500.0;
    double totalGastado = 0.0;
    String ultimoMovimiento = "---";

    try (BufferedReader br = new BufferedReader(new FileReader("DatosActualizados.txt"))) {
    String linea;
    String ultimaLinea = null;

    while ((linea = br.readLine()) != null) {
        ultimaLinea = linea;
        String[] partes = linea.split(",");
        if (partes.length >= 5) {
            double monto = Double.parseDouble(partes[3]);
            totalGastado += monto;
        }
    }

    if (ultimaLinea != null) {
        String[] partesUltima = ultimaLinea.split(",");
        String montoUltimo = partesUltima[3];
        String descripcionUltima = partesUltima[4];
        ultimoMovimiento = "S/ " + montoUltimo + " - " + descripcionUltima;
    }

} catch (IOException | NumberFormatException e) {
    e.printStackTrace();
}

    // Calculamos nuevo saldo
    double saldoActual = saldoInicial - totalGastado;

    // Mostramos en los JLabel
    lblSaldo.setText("Saldo actual: S/ " + String.format("%.2f", saldoActual));
    txtUltimo.setText("Último movimiento: \n" + ultimoMovimiento);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        jBtnPIN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUltimo = new javax.swing.JTextArea();
        jBtnSalir = new javax.swing.JButton();
        lblFechaHora = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PantallaPrincipal");
        setBackground(new java.awt.Color(245, 247, 250));

        lblBienvenida.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(28, 31, 74));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido, Usuario ");

        jBtnPIN.setBackground(new java.awt.Color(94, 96, 206));
        jBtnPIN.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jBtnPIN.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPIN.setText("Generar PIN de Seguridad");
        jBtnPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPINActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), "Resumen de cuenta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 14))); // NOI18N

        lblSaldo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblSaldo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Programa_Principal\\icons\\salary.png")); // NOI18N
        lblSaldo.setText("Saldo actual: S/ 0.00");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtUltimo.setEditable(false);
        txtUltimo.setBackground(new java.awt.Color(255, 255, 255));
        txtUltimo.setColumns(20);
        txtUltimo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtUltimo.setLineWrap(true);
        txtUltimo.setRows(5);
        txtUltimo.setWrapStyleWord(true);
        txtUltimo.setBorder(null);
        jScrollPane1.setViewportView(txtUltimo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jBtnSalir.setBackground(new java.awt.Color(239, 83, 80));
        jBtnSalir.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jBtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalir.setText("Salir del sistema");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        lblFechaHora.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(100, 100, 100));
        lblFechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaHora.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBienvenida)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jBtnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaHora)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jBtnPIN)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPIN)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaHora)
                .addGap(12, 12, 12)
                .addComponent(jBtnSalir)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPINActionPerformed
    pin = (int)(Math.random() * 9000) + 1000;
    
    try (FileWriter fw = new FileWriter("../ProgramaAuxiliar/Usuariodb.txt");
        BufferedWriter bw = new BufferedWriter(fw)){
        bw.write(nombreCompleto+","+numeroTelefonico+","+saldoInicial+","+pin);
        bw.newLine();
    }catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error de escritura");
    }
    
    
        JOptionPane.showMessageDialog(
        this,
        "🔒 Tu PIN de seguridad es: " + pin + "\n\n" +
        "Guarda este código en un lugar seguro y no lo compartas con nadie.\n" +
        "👉 Lo necesitarás para continuar con el siguiente proceso del sistema.",
        "PIN Generado",
        JOptionPane.WARNING_MESSAGE
        );     
    }//GEN-LAST:event_jBtnPINActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPIN;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextArea txtUltimo;
    // End of variables declaration//GEN-END:variables
}

